// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: internode_command.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InternodeCommand_MethodType int32

const (
	InternodeCommand_CONNECT     InternodeCommand_MethodType = 0
	InternodeCommand_SUBSCRIBE   InternodeCommand_MethodType = 1
	InternodeCommand_UNSUBSCRIBE InternodeCommand_MethodType = 2
)

// Enum value maps for InternodeCommand_MethodType.
var (
	InternodeCommand_MethodType_name = map[int32]string{
		0: "CONNECT",
		1: "SUBSCRIBE",
		2: "UNSUBSCRIBE",
	}
	InternodeCommand_MethodType_value = map[string]int32{
		"CONNECT":     0,
		"SUBSCRIBE":   1,
		"UNSUBSCRIBE": 2,
	}
)

func (x InternodeCommand_MethodType) Enum() *InternodeCommand_MethodType {
	p := new(InternodeCommand_MethodType)
	*p = x
	return p
}

func (x InternodeCommand_MethodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternodeCommand_MethodType) Descriptor() protoreflect.EnumDescriptor {
	return file_internode_command_proto_enumTypes[0].Descriptor()
}

func (InternodeCommand_MethodType) Type() protoreflect.EnumType {
	return &file_internode_command_proto_enumTypes[0]
}

func (x InternodeCommand_MethodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternodeCommand_MethodType.Descriptor instead.
func (InternodeCommand_MethodType) EnumDescriptor() ([]byte, []int) {
	return file_internode_command_proto_rawDescGZIP(), []int{0, 0}
}

type InternodeCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Method      InternodeCommand_MethodType `protobuf:"varint,2,opt,name=method,proto3,enum=mobisocial.omlet.avatar.InternodeCommand_MethodType" json:"method,omitempty"`
	Feed        *Feed                       `protobuf:"bytes,3,opt,name=feed,proto3" json:"feed,omitempty"`
	Subscribe   *SubscribeRequest           `protobuf:"bytes,4,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	Unsubscribe *UnsubscribeRequest         `protobuf:"bytes,5,opt,name=unsubscribe,proto3" json:"unsubscribe,omitempty"`
}

func (x *InternodeCommand) Reset() {
	*x = InternodeCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_command_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternodeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternodeCommand) ProtoMessage() {}

func (x *InternodeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internode_command_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternodeCommand.ProtoReflect.Descriptor instead.
func (*InternodeCommand) Descriptor() ([]byte, []int) {
	return file_internode_command_proto_rawDescGZIP(), []int{0}
}

func (x *InternodeCommand) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InternodeCommand) GetMethod() InternodeCommand_MethodType {
	if x != nil {
		return x.Method
	}
	return InternodeCommand_CONNECT
}

func (x *InternodeCommand) GetFeed() *Feed {
	if x != nil {
		return x.Feed
	}
	return nil
}

func (x *InternodeCommand) GetSubscribe() *SubscribeRequest {
	if x != nil {
		return x.Subscribe
	}
	return nil
}

func (x *InternodeCommand) GetUnsubscribe() *UnsubscribeRequest {
	if x != nil {
		return x.Unsubscribe
	}
	return nil
}

type InternodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Error       *Error             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Push        *Push              `protobuf:"bytes,3,opt,name=push,proto3" json:"push,omitempty"`
	Connect     *ConnectResult     `protobuf:"bytes,4,opt,name=connect,proto3" json:"connect,omitempty"`
	Subscribe   *SubscribeResult   `protobuf:"bytes,5,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	Unsubscribe *UnsubscribeResult `protobuf:"bytes,6,opt,name=unsubscribe,proto3" json:"unsubscribe,omitempty"`
}

func (x *InternodeReply) Reset() {
	*x = InternodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_command_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternodeReply) ProtoMessage() {}

func (x *InternodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_internode_command_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternodeReply.ProtoReflect.Descriptor instead.
func (*InternodeReply) Descriptor() ([]byte, []int) {
	return file_internode_command_proto_rawDescGZIP(), []int{1}
}

func (x *InternodeReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InternodeReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *InternodeReply) GetPush() *Push {
	if x != nil {
		return x.Push
	}
	return nil
}

func (x *InternodeReply) GetConnect() *ConnectResult {
	if x != nil {
		return x.Connect
	}
	return nil
}

func (x *InternodeReply) GetSubscribe() *SubscribeResult {
	if x != nil {
		return x.Subscribe
	}
	return nil
}

func (x *InternodeReply) GetUnsubscribe() *UnsubscribeResult {
	if x != nil {
		return x.Unsubscribe
	}
	return nil
}

var File_internode_command_proto protoreflect.FileDescriptor

var file_internode_command_proto_rawDesc = []byte{
	0x0a, 0x17, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x6d, 0x6f, 0x62, 0x69, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x2e, 0x6f, 0x6d, 0x6c, 0x65, 0x74, 0x2e, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x1a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xae, 0x02, 0x0a, 0x10, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x6f, 0x64, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x4c, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x73, 0x6f, 0x63,
	0x69, 0x61, 0x6c, 0x2e, 0x6f, 0x6d, 0x6c, 0x65, 0x74, 0x2e, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x19, 0x0a, 0x04, 0x66, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x52, 0x04, 0x66, 0x65, 0x65, 0x64, 0x12,
	0x2f, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x12, 0x35, 0x0a, 0x0b, 0x75, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x75, 0x6e, 0x73, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x22, 0x39, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x10,
	0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45,
	0x10, 0x02, 0x22, 0xe9, 0x01, 0x0a, 0x0e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x04, 0x70, 0x75, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x52, 0x04, 0x70, 0x75, 0x73, 0x68, 0x12, 0x28,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x2e, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x09, 0x73,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x75, 0x6e, 0x73, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x0b, 0x75, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x42, 0x0d,
	0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internode_command_proto_rawDescOnce sync.Once
	file_internode_command_proto_rawDescData = file_internode_command_proto_rawDesc
)

func file_internode_command_proto_rawDescGZIP() []byte {
	file_internode_command_proto_rawDescOnce.Do(func() {
		file_internode_command_proto_rawDescData = protoimpl.X.CompressGZIP(file_internode_command_proto_rawDescData)
	})
	return file_internode_command_proto_rawDescData
}

var file_internode_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internode_command_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internode_command_proto_goTypes = []interface{}{
	(InternodeCommand_MethodType)(0), // 0: mobisocial.omlet.avatar.InternodeCommand.MethodType
	(*InternodeCommand)(nil),         // 1: mobisocial.omlet.avatar.InternodeCommand
	(*InternodeReply)(nil),           // 2: mobisocial.omlet.avatar.InternodeReply
	(*Feed)(nil),                     // 3: Feed
	(*SubscribeRequest)(nil),         // 4: SubscribeRequest
	(*UnsubscribeRequest)(nil),       // 5: UnsubscribeRequest
	(*Error)(nil),                    // 6: Error
	(*Push)(nil),                     // 7: Push
	(*ConnectResult)(nil),            // 8: ConnectResult
	(*SubscribeResult)(nil),          // 9: SubscribeResult
	(*UnsubscribeResult)(nil),        // 10: UnsubscribeResult
}
var file_internode_command_proto_depIdxs = []int32{
	0,  // 0: mobisocial.omlet.avatar.InternodeCommand.method:type_name -> mobisocial.omlet.avatar.InternodeCommand.MethodType
	3,  // 1: mobisocial.omlet.avatar.InternodeCommand.feed:type_name -> Feed
	4,  // 2: mobisocial.omlet.avatar.InternodeCommand.subscribe:type_name -> SubscribeRequest
	5,  // 3: mobisocial.omlet.avatar.InternodeCommand.unsubscribe:type_name -> UnsubscribeRequest
	6,  // 4: mobisocial.omlet.avatar.InternodeReply.error:type_name -> Error
	7,  // 5: mobisocial.omlet.avatar.InternodeReply.push:type_name -> Push
	8,  // 6: mobisocial.omlet.avatar.InternodeReply.connect:type_name -> ConnectResult
	9,  // 7: mobisocial.omlet.avatar.InternodeReply.subscribe:type_name -> SubscribeResult
	10, // 8: mobisocial.omlet.avatar.InternodeReply.unsubscribe:type_name -> UnsubscribeResult
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_internode_command_proto_init() }
func file_internode_command_proto_init() {
	if File_internode_command_proto != nil {
		return
	}
	file_command_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_internode_command_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternodeCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internode_command_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internode_command_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internode_command_proto_goTypes,
		DependencyIndexes: file_internode_command_proto_depIdxs,
		EnumInfos:         file_internode_command_proto_enumTypes,
		MessageInfos:      file_internode_command_proto_msgTypes,
	}.Build()
	File_internode_command_proto = out.File
	file_internode_command_proto_rawDesc = nil
	file_internode_command_proto_goTypes = nil
	file_internode_command_proto_depIdxs = nil
}
